### ISSUE TITLE
vae to stable diffusion error

### ISSUE THREAD

**Issue by yanhuifair** [akashsara/fusion-dance#15]
When I try to train my own sprite image, I put the image in the test, training and Val folder, the image is 512*512 size, then after I run the vq_vae.py script, I get a .pt file, but when I want to use it .pt flie to stable diffusion, I get an error, such as the image below, how can I use this vae in stable diffusion, thank you!

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/8871751/233052493-2215a7f0-d17d-4546-9e11-48f97c97aac0.png">

There are also some screenshots that I don't know if they are useful
<img width="389" alt="image" src="https://user-images.githubusercontent.com/8871751/233055418-440da030-2e1b-49f9-86e0-657b949e350e.png">
<img width="787" alt="image" src="https://user-images.githubusercontent.com/8871751/233055547-0274dff5-574a-4c81-bd3f-2061ce898359.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/8871751/233055580-65c29674-1d41-459c-9a41-e4693f891d0b.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/8871751/233055608-2eaf549e-492d-4b85-b635-5e8da466466f.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/8871751/233055647-1077bdf7-ed82-4aa7-9df6-7cf2181cf170.png">

**Comment by akashsara** [comment]
It looks to me like you're using two different architectures. The VQ-VAE from this repo has a different architecture to the AutoencoderKL in your image. You need to use the same one in both cases.

**Comment by yanhuifair** [comment]
> It looks to me like you're using two different architectures. The VQ-VAE from this repo has a different architecture to the AutoencoderKL in your image. You need to use the same one in both cases.

What should I do if I want to use your research on stable diffusion, I'm an artist who doesn't know much about machine learning, thank you very much for your guidance, think you Akash Saravanan

**Comment by akashsara** [comment]
Unfortunately I haven't really had the chance to go through the Stable Diffusion code to properly understand things there, so I don't really know. My best guess at this point would be that you would have to replace AutoencoderKL with the VQ-VAE defined in this repo.

**Comment by yanhuifair** [comment]
> Unfortunately I haven't really had the chance to go through the Stable Diffusion code to properly understand things there, so I don't really know. My best guess at this point would be that you would have to replace AutoencoderKL with the VQ-VAE defined in this repo.

Thank you for your reply, I'll try, thank you for creating this great library and research!
